services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mypack_database
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
  db_admin:
    depends_on:
      - db
    image: phpmyadmin:5.0
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
  server:
    image: quay.io/wildfly/wildfly
    ports:
      - 8082:8080
    volumes:
      - ./target/myPack-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/myPack-1.0-SNAPSHOT.war
volumes:
  db_volume: